name: mafia_education_app
version: 1.0.0+1
publish_to: none
description: Mafia Education Application Project
environment:
    sdk: '>=2.19.6 <3.0.0'

dependencies:
    cupertino_icons: ^1.0.2
    get: 4.6.5
    flutter:
        sdk: flutter
    flutter_native_splash: ^2.2.19

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/images/

flutter_native_splash:
    color: '#ffffff'
    image: assets/images/logo.png
    android_12:
        color: '#ffffff'
        image: assets/images/logo.png
    android: true
    ios: true
    web: false
